name:                hpuzzle
version:             0.1.0.0
github:              "aldanaramirez/hpuzzle"
license:             BSD-3-Clause
author:              "Aldana Ramirez"
maintainer:          "aldanaramirez19@gmail.com"
copyright:           "2025 Aldana Ramirez"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/hpuzzle#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- mtl
- csp

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  hpuzzle-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hpuzzle

tests:
  hpuzzle-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hpuzzle
    - hspec
    - hspec-discover
